services:
  oracle-log-exporter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oracle-log-exporter
    env_file:
      - .env
    volumes:
      - ./output:/app/output
      - ./state:/app/state
    restart: unless-stopped
